### ISSUE TITLE
Split into multiple maven modules

### ISSUE THREAD

**Issue by Toilal** [benas/jPopulator#26]
In most case, jPopulator is used in unit tests cases, but annotations are included in Java Beans of application.

It would be better to split the project into a maven multi-module project, at least to have a standalone module for annotations.

Also for the spring-context dependency and spring related stuff.

**Comment by Toilal** [comment]
Something like this : 

```
|- jpopulator (pom)
  |- jpopulator-core (jar)
  |- jpopulator-annotations (jar)
  |- jpopulator-spring (jar)
```

**Comment by benas** [comment]
Hi @Toilal ,

Thank you for your suggestion, in fact, the code base should be modular like this.

I'll plan that for next release.

Cheers
Mahmoud
