### ISSUE TITLE
PopulatorBuilder.build() should really build instances

### ISSUE THREAD

**Issue by Toilal** [benas/jPopulator#27]
Currently, PopulatorBuilder.build() always returns the same instance. It can lead to issues like this one : 

```java
PopulatorBuilder builder = new PopulatorBuilder();
Populator defaultPopulator = builder.build();

builder.registerRandomizer(...) // Register some randomizer
Populator customPopulator = builder.build();

// but defaultPopulator == customPopulator
// and defaultPopulator use the registered randomizer
```

**Comment by benas** [comment]
Hello,

I'm not sure this is an issue, the builder is designed to build only one instance, it is not a reusable object. I even saw some projects throwing `IllegalStateException` if you call any method ofter the build method has been called and the instance was built.

Anyway, we can reset its state and make it reusable as you have done in your PR.

Thank you for your awesome contributions!

Regards
Mahmoud
