### ISSUE TITLE
MapRandomizer.checkArguments

### ISSUE THREAD

**Issue by didine** [benas/jPopulator#37]
Class: MapRandomizer
method:  checkArguments(int minElements, int maxElements)

Issue desc: 
checkArguments is throwing unjustified ecxeptions because of a wrong check at second "if".
Instead of " if (minElements < 1)" it should be " p if (maxElements < 1)".

**Comment by benas** [comment]
Thank you for pointing out this issue! 
Indeed it should check the maxElements parameter according to the error message.
I'll fix that. Thank you :+1:

**Comment by benas** [comment]
Hello,

Just fixed this issue and published the fix in maven central (version 1.3.0-SNAPSHOT).
It will be released soon, keep tuned.

Regards
Mahmoud
